version: "3"

services:
  app:
    build:
      context: ./env/nginx
    ports:
      - 8080:8080
    volumes:
      - tmp-uds:/tmp
  api:
    build:
      context: ./env/golang
    volumes:
      - ./src/keeown-api:/go/src/keeown-api
      - tmp-uds:/tmp
    command: ["go", "run", "main.go"]
  ui:
    build:
      context: ./env/node
    volumes:
      - ./src/keeown-ui:/home/node/ui
    command: ["yarn", "serve"]
volumes:
  tmp-uds:
